#!/bin/sh

set -eu

get_download_file_name() {
  os=$1
  file_name=aws-profile-macos
  if [ "${os}" = "Linux" ]; then
    file_name=aws-profile-linux
  fi
  echo ${file_name}
}

OS=$(uname -s)
if [ "${OS}" != "Darwin" ] && [ "${OS}" != "Linux" ]; then
  echo "${OS} is not supported"
  exit 1
fi

TMP_DIR=$(mktemp -d /tmp/aws-profile.XXXXXX)
TARGET_FILE="/usr/local/bin/aws-profile"
DOWNLOAD_FILE_NAME=$(get_download_file_name ${OS})
URL="$(curl -s https://api.github.com/repos/hpcsc/aws-profile/releases/latest | \
        grep browser_download_url | \
        grep ${DOWNLOAD_FILE_NAME} | \
        cut -d '"' -f 4)"

if [ -e "${TARGET_FILE}" ]; then
  echo "aws-profile exists at ${TARGET_FILE}, cancel? (Y/n)"
  read confirm_cancel
  confirm_cancel=${confirm_cancel:-y}
  if [ "${confirm_cancel}" = "y" ] || [ "${confirm_cancel}" = "Y" ]; then
    exit 0
  fi;
fi

(
  cd "$TMP_DIR"

  echo "Downloading from ${URL}..."
  curl -fLO "${URL}"
  echo "Download complete!"
)

(
  mv -vf "${TMP_DIR}/${DOWNLOAD_FILE_NAME}" "${TARGET_FILE}"
  chmod +x "${TARGET_FILE}"
)

rm -rf "$TMP_DIR"

echo "aws-profile is installed successfully 🎉"
