name: Master Build and Publish
on:
  push:
    branches:
      - master

jobs:
  commit:
    name: Commit
    runs-on: ubuntu-18.04
    steps:
    - name: Check out
      uses: actions/checkout@v1

    - name: Build
      run: |
        ./batect build-linux

    - name: Lint
      run: |
        ./batect lint

    - name: Test
      run: |
        ./batect test

    - name: Scan security
      run: |
        ./batect scan-security

    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.txt
        flags: unittests
        name: aws-profile-coverage
        fail_ci_if_error: true
        verbose: true

    - name: Generate coverage html report
      run: |
        ./batect generate-coverage-report

    - name: Run E2E Test
      run: |
        ./batect e2e -- bin/aws-profile-${{runner.os}}-${{github.sha}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload coverage html report as artifact
      uses: actions/upload-artifact@v1
      with:
        name: coverage-html-report
        path: ./coverage.html

  publishLinux:
    name: Publish Linux
    runs-on: ubuntu-18.04
    needs: commit
    steps:
    - name: Check out
      uses: actions/checkout@v1

    - name: Build for Linux
      run: |
        ./batect build-linux
      env:
        VERSION_NUMBER: ${{github.sha}}
        OUTPUT: bin/aws-profile-linux

    - name: Upload Linux binary as artifact
      uses: actions/upload-artifact@v1
      with:
        name: aws-profile-linux
        path: ./bin/aws-profile-linux


  publishMacOS:
    name: Publish MacOS
    runs-on: ubuntu-18.04
    needs: commit
    steps:
    - name: Check out
      uses: actions/checkout@v1

    - name: Build for MacOS
      run: |
        ./batect build-macos
      env:
        VERSION_NUMBER: ${{github.sha}}
        OUTPUT: bin/aws-profile-macos

    - name: Upload MacOS binary as artifact
      uses: actions/upload-artifact@v1
      with:
        name: aws-profile-macos
        path: ./bin/aws-profile-macos

  publishWindows:
    name: Publish Windows
    runs-on: ubuntu-18.04
    needs: commit
    steps:
    - name: Check out
      uses: actions/checkout@v1

    - name: Build for Windows
      run: |
        ./batect build-windows
      env:
        VERSION_NUMBER: ${{github.sha}}
        OUTPUT: bin/aws-profile-windows

    - name: Upload Windows binary as artifact
      uses: actions/upload-artifact@v1
      with:
        name: aws-profile-windows
        path: ./bin/aws-profile-windows

  uploadToArtifactory:
    name: Upload to Artifactory
    runs-on: ubuntu-18.04
    needs: [publishLinux, publishMacOS, publishWindows]
    steps:
    - name: Check out
      uses: actions/checkout@v1

    - name: Download all artifacts
      uses: actions/download-artifact@v2
      with:
        path: artifacts

    - name: Show downloaded artifacts
      run: ls -laR ./artifacts

    - name: Upload
      run: |
        ./batect upload-to-artifactory
      env:
        VERSION_NUMBER: ${{github.sha}}
        ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
